### ISSUE TITLE
Bleaching messes with paragraphs

### ISSUE THREAD

**Issue by scribu** [erwinmatijsen/django-markdownify#10]
### Steps to reproduce

Say I have a `description` variable with the following content:

```
A short paragraph.

Another paragraph.
```

In my template, I have `{{description|markdownify}}`.

### Expected output

```
<p>A short paragraph.</p>
<p>Another paragraph.</p>
```

### Actual output

```
A short paragraph.
Another paragraph.
```

This is definitely *not* what I expected. One of the main reasons for using Markdown in the first place is to avoid manually inserting paragraphs.

If I set `MARKDOWNIFY_BLEACH = False` in my settings, I get the correct output.

**Comment by erwinmatijsen** [comment]
I can't seem to reproduce your problem, i.e. I get the expected output.
Can you show your `MARKDOWNIFY_WHITELIST_TAGS`?

**Comment by scribu** [comment]
I did not have `MARKDOWNIFY_WHITELIST_TAGS` defined.

But if I set it to the value in the README, i.e. including the `p` tag, I get the correct output.

**Comment by erwinmatijsen** [comment]
Yes, if you don't set `MARKDOWNIFY_WHITELIST_TAGS` it will use the default allowed tags from bleach, which doesn't include `p` (see [this section](https://bleach.readthedocs.io/en/latest/clean.html#allowed-tags-tags) in the bleach docs).
