### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by EnriqueSoria** [erwinmatijsen/django-markdownify#12]
It is common that editors that support markdown also support emojis, using codes like `:+1: ` which translates to corresponding emoji :+1:

**Comment by erwinmatijsen** [comment]
`django-markdownify` accepts a list of extensions to be used. You can implement emoji support with for example [this extension](https://github.com/EloiseSeverin/markdown_markup_emoji).
See [the documentation](https://django-markdownify.readthedocs.io/en/latest/settings.html) for more information.
