### ISSUE TITLE
Fix indentation in install_and_usage so it works when copying & pasting into views.py

### ISSUE THREAD

**Issue by yemarnevets** [erwinmatijsen/django-markdownify#14]
On this docs page, [install_and_usage.rst](https://django-markdownify.readthedocs.io/en/latest/install_and_usage.html), the indentation is odd and does not work when copying and pasting into views.py. I attempted to open a pull request but I do not have permission to push to a new branch.

**Comment by erwinmatijsen** [comment]
I fixed the indentation in the docs. I will look into why you couldn't push to a new branch.
