### ISSUE TITLE
Are Headings Not Supported? 

### ISSUE THREAD

**Issue by yemarnevets** [erwinmatijsen/django-markdownify#22]
I'd like to easily utilize headings in Django-Markdownify. I can work on this if necessary, but this seems like quite a drawback. 

E.g., if I had:

`### FooBarBob`

When I run 'markdownify' I'd expect this to get translated to: 

`<h3>FooBarBob</h3>`

Please see https://www.markdownguide.org/basic-syntax/ with any questions or let me know.

Cheers,
Yemar

**Comment by erwinmatijsen** [comment]
Please [read the docs](https://django-markdownify.readthedocs.io/en/latest/settings.html#whitelist-tags) on how to enable headings (and other tags).

**Comment by yemarnevets** [comment]
This documentation is super useful. I did not expand "Settings" originally so thanks for pointing that out. I had to go through another website to find the WHITELIST info after posting this question and I am up and running. Could you please add something about the settings and additional configuration these to the main documentation? **For newcomers, the design decision to only enable a subset of markdown is confusing and non-obvious.** It is my fault for not rigorously checking the documentation, of course, but my assumption based on the sparse landing page was that all markdown will be enabled or whitelisted by default (e.g,. this page: https://django-markdownify.readthedocs.io/en/latest/index.html). I can submit a PR, but this seems like some documentation that would benefit from your expertise and elucidating upon the design decisions. Even a "for configuring which markdown is rendered check out settings" would be much improved. Now that I have it up and working, I love django-markdownify and I will go to the hills and spread the gospel. Thanks!

**Comment by erwinmatijsen** [comment]
You are totally right. I'm in the proces of updating the docs for some new features, so I will include some clarification about the defaults.
