### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by davekch** [erwinmatijsen/django-markdownify#24]
when I installed this with `pip install django-markdownify`, none of the `*.md` files in the tests directory were downloaded so all tests fail with `FileNotFoundError`.

**Comment by erwinmatijsen** [comment]
I see `package_data` is missing from `setup.py`, will add it.

**Comment by erwinmatijsen** [comment]
Added in [pull request 25](https://github.com/erwinmatijsen/django-markdownify/pull/25) and uploaded to pypi.
