### ISSUE TITLE
line breaks 

### ISSUE THREAD

**Issue by gurugeek** [erwinmatijsen/django-markdownify#26]
First of all thank you for your package :) 👍  all the Markdown parsers for Django seems to be 8+ years old at least : 🌊 
Quick question: how can I rended line breaks ?

At the moment I am using 
{{ value|markdownify|linebreaksbr }}

but perhaps there is a better way? 
Thanks!

**Comment by gurugeek** [comment]
figured it out you need to add

MARKDOWNIFY_MARKDOWN_EXTENSIONS = ['markdown.extensions.nl2br']

**Comment by loleg** [comment]
The recommended way to configure extensions would work like this:

```python
MARKDOWNIFY = {
        "default": {
            "MARKDOWN_EXTENSIONS": [
                "markdown.extensions.nl2br",
            ]
        }
    }
```

However, this does not have an effect for me. I have to still use the `|linebreaksbr` filter.

**Comment by fertek** [comment]
This works for me:

```
MARKDOWNIFY = {
    "default": {
        "WHITELIST_TAGS": [
            'br',
        ],
        "MARKDOWN_EXTENSIONS": {
            "markdown.extensions.nl2br",
        },
    }
}
```
