### ISSUE TITLE
Rendering of a table not possible

### ISSUE THREAD

**Issue by n2o** [erwinmatijsen/django-markdownify#27]
Hello,

I am looking for a Markdown library, which makes it possible to render tables from markdown. Your lib seems to be not capable of this feature, am I right in this point?

What I have tried so far:

1. Installed markdownify from pypi
```
"django-markdownify": {
            "hashes": [
                "sha256:28ee91769c97a7374716ce0fd1dcd3094fc3405af8b876db88e9787401adb40b",
                "sha256:42de7e691c0a9239bda8540de57a254d70c938bdb09f514dcafa9c197a06e6fa"
            ],
            "index": "pypi",
            "version": "==0.8.2"
        }
```

2. Using Django 2.2.17
3. Enabling markdownify in a template of the static-page app:

```python
# ...
{% load markdownify %}

{% block heading %}
  <h1>{{ page.title }}</h1>
{% endblock %}

{% block content %}
  <p>
    {{ page.content|markdownify }}
  </p>
{% endblock %}
```
4. Input value for the table:
```
| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |


**verify that markdown is rendered**
```
5. Result:
![image](https://user-images.githubusercontent.com/1507474/105641429-3bfc0c00-5e84-11eb-8306-d5d2a56fd73a.png)

Do you have any ideas on this issue? Or is simply not possible to render tables with your library?

Thanks :-)

**Comment by erwinmatijsen** [comment]
In your settings you need to whitelist all table-related tags, e.g.

```
MARKDOWNIFY_WHITELIST_TAGS = [
    'table',
    'thead',
    'tbody',
    'th',
    'tr',
    'td',
]
```

Also add the `extras` extension (also in your settings), which contains the [`tables` extension](https://python-markdown.github.io/extensions/tables/):

```
MARKDOWNIFY_MARKDOWN_EXTENSIONS = ['markdown.extensions.extra', ]
```
Your table now should be rendered.

**Comment by n2o** [comment]
hey, thanks, that did the trick. Thanks for the fast support!
