### ISSUE TITLE
Can I add a class to a table?

### ISSUE THREAD

**Issue by n2o** [erwinmatijsen/django-markdownify#28]
Heyho, is it possible to add a CSS class to a table or something?

I can configure as allowed attributes the following settings:

```
MARKDOWNIFY_WHITELIST_ATTRS = [
    'href',
    'src',
    'alt',
    'class',
]
```

In my case, I want to add `table table-hover table-striped` classes to a table, but I do not know how to do this. And I can only find it in the python code examples, but not from within the markdown itself. Is it possible to add classes?

Your documentation points to this page: https://bleach.readthedocs.io/en/latest/clean.html#allowed-attributes-attributes
But they are using the attrs on the html code itself, not on markdown representations.

Thanks for your help :)

**Comment by erwinmatijsen** [comment]
I think [the attribute list](https://python-markdown.github.io/extensions/attr_list/) extension will do what you want. It is included in the `extra` extension. Can you give it a shot and let me know how it worked out?

**Comment by n2o** [comment]
Hm, jep I came up with this page, but it doesn't work, because the devs of python markdown don't want it.

https://github.com/Python-Markdown/markdown/issues/312

**Comment by erwinmatijsen** [comment]
I see. Well, `django-markdownify` is a small wrapper around `python-markdown` and `bleach`. So if the underlying libs don't have support for it, `django-markdownify` won't support it either.

Maybe there are some extenstions to `python-markdown` with better table support? Otherwise there's always the option to just write the html in your Markdown-file.

**Comment by n2o** [comment]
Hm, in the issue there are several people talking about alternatives, but they oftentimes don't fulfill the necessary requirements. I will check some of them.

The Editing-Feature is for non-technical people, and I do not think that they are able to write HTML tables without a real editor. I tested it with a small table, but this is not a valuable solution. For me this will be no problem, but there are some more people writing posts on the page.

Thanks for your help. I will keep an eye on the other extensions and leave you a comment, if there is a working solution 👍
