### ISSUE TITLE
Issues with providing alternative settings

### ISSUE THREAD

**Issue by ActuallyTaylor** [erwinmatijsen/django-markdownify#29]
I followed the setup in the [documentation](https://django-markdownify.readthedocs.io/en/latest/), however whenever I place `{{ content|markdownify:"alternative" }}` into my index.html folder I get the error `markdownify requires 1 arguments, 2 provided`. Markdownify works perfectly when it is not given alternative settings.

**Comment by erwinmatijsen** [comment]
Did you upgrade `django-markdownify` to the latest version (0.9.0)? Older versions won't work with alternative settings. Try to run `python3 -m pip install --upgrade django-markdownify`.

**Comment by ActuallyTaylor** [comment]
Yep that worked, I have no clue why pip was not installing the latest version when I asked it to update it before but your command worked great. Thank you!
