### ISSUE TITLE
Conflicting Python package names

### ISSUE THREAD

**Issue by shuki25** [erwinmatijsen/django-markdownify#34]
I cannot use your package and the following package at the same time:

[ matthewwithanm / python-markdownify ](https://github.com/matthewwithanm/python-markdownify)

and yours.  Both has the conflicting package names. I use both packages in my django project.  Somehow it works on my development machine but it breaks if I package it into Docker image.

```
File "/edscc/edscc/core/utils.py", line 16, in <module>
    from markdownify import markdownify as md
ImportError: cannot import name 'markdownify' from 'markdownify' (/usr/local/lib/python3.7/site-packages/markdownify/__init__.py)
```

Your package overwrites matthewwithanm's package when building a docker image.

Recommended fix is to rename your package folder to something else so it doesn't conflict with the above package.

**Comment by erwinmatijsen** [comment]
Will [pip install --target](https://pip.pypa.io/en/stable/cli/pip_install/#options) help?

So install python-markdownify to an alternative dir (e.g. `p_markdownify`) and import from there:

`from p_markdownify import markdownify as md`
