### ISSUE TITLE
module 'bleach.sanitizer' has no attribute 'ALLOWED_STYLES'

### ISSUE THREAD

**Issue by jspaans91** [erwinmatijsen/django-markdownify#35]
Since Bleach version 5.0.0 the sanitation of CSS style tags is completely refactored and placed in a separate package. Therefore the attribute ‘ALLOWED_STYLES’ is completely removed and is not accepted anymore.

This causes the following error when using this package:

`module 'bleach.sanitizer' has no attribute 'ALLOWED_STYLES' `

**Comment by rhimmelbauer** [comment]
Thanks for @jspaans91 putting up the issue @jspaans91. @erwinmatijsen when do you think we could get an update for it? :)

**Comment by jtauber** [comment]
I'm wondering if it's worth pinning dependency versions to prevent this sort of thing in the future.

**Comment by jspaans91** [comment]
@jtauber and @jtauber I created a pull request with a quickfix that pins de requirement to a version below 5.0.0.

So when @erwinmatijsen the pull requests accepts the issue is temporary fixed.

**Comment by erwinmatijsen** [comment]
Thanks for the pull request. I'll have to look into the issue to make a permanent fix.

**Comment by jspaans91** [comment]
@erwinmatijsen can you also publish a new release for this quickfix version? So the this version can be installed with the package installer.

**Comment by coredumperror** [comment]
Seconding the request for a quick-fix version being put up on PyPi.

**Comment by erwinmatijsen** [comment]
Pushed updated version to PyPi

**Comment by rob32** [comment]
i made a PR #37 to work with bleach's new CSS sanitize. Should be best tested again.
The defautt whitelist can be found here: [main/bleach/css_sanitizer.py](https://github.com/mozilla/bleach/blob/main/bleach/css_sanitizer.py)

**Comment by erwinmatijsen** [comment]
I merged the PR, made some minor changes and updated the docs.
