### ISSUE TITLE
Passing `extension_configs` to python-markdown

### ISSUE THREAD

**Issue by FRiMN** [erwinmatijsen/django-markdownify#38]
Hi!
Why django-markdownify dont pass `extension_configs` to python-markdown?

As far as I understand, now there is no way to pass any settings to extensions.

See: https://github.com/Python-Markdown/markdown/blob/master/markdown/core.py#L97

**Comment by erwinmatijsen** [comment]
See [updated docs](https://django-markdownify.readthedocs.io/en/latest/settings.html#enable-markdown-extensions) to read how it works.
