### ISSUE TITLE
How to add a classs to image.

### ISSUE THREAD

**Issue by AlekseiKondrashov** [erwinmatijsen/django-markdownify#50]

**Comment by erwinmatijsen** [comment]
In Markdown, you can´t add classes to images. Maybe there is an [extension](https://python-markdown.github.io/extensions/) available that adds that functionality, but not that I'm aware of. If you find (or write) such an extension, don't forget to update the [markdownify settings](https://django-markdownify.readthedocs.io/en/latest/index.html) by whitelisting the `img` tag in `WHITELIST_TAGS` and `src` and `class` in `WHITELIST_ATTRS`.

You can always just write out the HTML in your Markdown document, e.g `<img class="my-class" src=".."/>`
