### ISSUE TITLE
Documention could suggest using `filter markdownify`.

### ISSUE THREAD

**Issue by trevoriancox** [erwinmatijsen/django-markdownify#56]
As currently documented, django-markdownify won't work with template tags. But you can use `{% filter markdownify %}` instead of `{% markdownify %}`. In that case, Python-Markdown will process the text after the template substitution, and dynamic content will work, e.g.

`<https://{{ domain }}/help/flyer.pdf>`

**Comment by erwinmatijsen** [comment]
Although it seems to work, it for some reason puts all text in a `<pre>` and `<code>` block. Did you experience that as well?

**Comment by trevoriancox** [comment]
> Although it seems to work, it for some reason puts all text in a `\<pre\>` and `<code>` block. Did you experience that as well?

No, I did not notice that. Seemed to work very well.

**Comment by erwinmatijsen** [comment]
I found out why it puts it in `<pre>` and` <code>` blocks. It has to do with indentation; when I neatly indent everything in a template, it adds a lot of spaces before the text, and then it apparently doesn't parse it correctly.

So this doesn't work:

```
<section class="section">
  <div class="container content">
    {% filter markdownify %}
        [test](https://{{ domain }}/help/flyer.pdf)
    {% endfilter %}
  </div>
</section>
```

But this does:

```
<section class="section">
    <div class="container content">
{% filter markdownify %}
[test](https://{{ domain }}/help/flyer.pdf)
{% endfilter %}
    </div>
</section>
```

Can you reproduce this, or is it something weird in my setup?

**Comment by trevoriancox** [comment]
That sounds like the correct behaviour: "The basic Markdown syntax allows you to create code blocks by indenting lines by four spaces or one tab."

**Comment by erwinmatijsen** [comment]
Ofcourse! I'm not used to use indentation for codeblocks, and certainly not used to use MD in my templates. 

I will add the use of `filter` to the docs.

**Comment by erwinmatijsen** [comment]
Updated docs
