### ISSUE TITLE
Support for markdown extensions?

### ISSUE THREAD

**Issue by bitphage** [erwinmatijsen/django-markdownify#6]
I found that multi-lined fenced code blocks doesn't working out of the box. How about adding support of markdown extension to load?

settings:
```python
MARKDOWNIFY_MARKDOWN_EXTENSIONS = ['markdown.extensions.fenced_code']
```

module:
```python
 html = markdown.markdown(text, extensions=MARKDOWNIFY_MARKDOWN_EXTENSIONS)
```

**Comment by erwinmatijsen** [comment]
Thanks, I will look into it!

**Comment by erwinmatijsen** [comment]
Added the option to add extensions to markdown.
