### ISSUE TITLE
MARKDOWNIFY_WHITELIST_ATTRS style color

### ISSUE THREAD

**Issue by Hugo-Trentesaux** [erwinmatijsen/django-markdownify#7]
Hello, 
In your README you do not precise how to set the attributes for the style attributes.
As written in the bleach doc :
``` python
>>> attrs = {
...     '*': ['style']
... }
>>> styles = ['color', 'font-weight']
```
Is it possible with your markdownify or should I modify it ?
Thanks !

[edit] I just created a pull request [/edit]

**Comment by erwinmatijsen** [comment]
Thanks, changes are merged. Will update readme soon.
