### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ALLOWED_TAGS'

### ISSUE THREAD

**Issue by ursomniac** [erwinmatijsen/django-markdownify#9]
This is with the installation instructions followed, also with Markdown==2.6.7 and bleach==1.5.0 installed.

**Comment by erwinmatijsen** [comment]
<del>The code on github is ahead of the pypi package, which I haven't got the time to update yet.
When you install the package not from pypi, but from github all should be fine. </del>

<del>Will update pypi as soon as possible</del>

**EDIT**
Scratch that, that shouldn't be a problem. I mistakenly thought about recently added changes, but those were for allowed styles. Let me get back to you.

**Comment by erwinmatijsen** [comment]
Please update bleach to at least version 2.0. 

I'll update the requirements.
